/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

public class Library
{
    public static void main(String[] args)
    {
        Restaurant testRestaurant = new Restaurant("TEST NAME", 4, 3);
        Review testReview1 = new Review("TEST", "Test Author", 4);
        Review testReview2 = new Review("TEST", "Test Author", 4);
        Review testReview3 = new Review("TEST", "Test Author", 4);

        testRestaurant.addReview(testReview1);
        testRestaurant.addReview(testReview2);
        testRestaurant.addReview(testReview3);

        System.out.println(testRestaurant.toString());
        System.out.println(testReview1.toString());
        System.out.println(testRestaurant.reviews.toString());
    }
}
