/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import java.util.ArrayList;
import java.util.List;

public class Library
{
    public static void main(String[] args)
    {
        Theater theater = new Theater();
        List<String> testMovieList = new ArrayList<>();

        theater = new Theater("TEST THEATER", testMovieList, 4.0);


        theater.movieList.add("Movie 1");

        System.out.println(theater.movieList);

        theater.movieList.add("Movie 2");
        theater.movieList.add("Movie 3");
        theater.movieList.add("Movie 1");

        System.out.println(theater.movieList);

        theater.movieList.remove("Movie 1");

        System.out.println(theater.movieList);

        theater.removeMovie("Movie 1");

        System.out.println(theater.movieList);

        theater.addMovie("Movie 1");
        theater.addMovie("Movie 4");

        System.out.println(theater.movieList);

        System.out.println(theater.toString());

        TheaterReview testTheaterReview1 = new TheaterReview("TEST BODY 1", "Test Author 1", 4.0, theater);

        System.out.println(testTheaterReview1.movie);


    }
}
