/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import java.io.*;
import java.util.*;

public class App {

    public static void main(String[] args) {
        String filePath = "./resources/empty.js";
        System.out.println(linter(filePath));
    }

    public static String linter(String filePath) {
        Scanner scanner = null;

        StringBuilder outputMessage = new StringBuilder();
        int lineCount = 1;
        int errorCount = 0;

        // Targeted symbols.
        String semicolon = ";";
        String openingBracket = "{";
        String closingBracket = "}";
        String ifCheck = "if";
        String elseCheck = "else";

        try {
            scanner = new Scanner(new BufferedReader(new FileReader(filePath)));

            while (scanner.hasNextLine()) {
                String nextLine = scanner.nextLine();
                if (
                    (nextLine.length() > 0) &&
                    !((nextLine.endsWith(semicolon)) ||
                    (nextLine.endsWith(openingBracket)) ||
                    (nextLine.endsWith(closingBracket)) ||
                    (nextLine.contains(ifCheck)) ||
                    (nextLine.contains(elseCheck)))
                ) {
                    errorCount++;
                    outputMessage
                            .append("Line ")
                            .append(lineCount)
                            .append(": Missing semicolon.\n");
                }
                lineCount++;
            }
        } catch (FileNotFoundException error) {
            return "The file was not found.";
        } finally {
            if (scanner != null) {
                scanner.close();
            }
        }
        outputMessage
                .append("Error Count: ")
                .append(errorCount)
                .append("\n");
        return outputMessage.toString();
    }
}
