/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.Before;
import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest
{
    Restaurant testRestaurant;
    Review testReview1;
    Review testReview2;
    Review testReview3;

    @Before
    public void initializeTestData()
    {
        String testName = "TEST RESTAURANT";
        int testStarsRestaurant = 4;
        int testPriceCategory = 3;
        testRestaurant = new Restaurant(testName, testStarsRestaurant, testPriceCategory);

        testReview1 = new Review("TEST BODY 1", "Test Author 1", 4);
        testReview2 = new Review("TEST BODY 2", "Test Author 2", 3);
        testReview3 = new Review("TEST BODY 3", "Test Author 3", 2);

        testRestaurant.addReview(testReview1);
        testRestaurant.addReview(testReview2);
        testRestaurant.addReview(testReview3);
    }

    @Test
    public void testRestaurant()
    {
        assertTrue("Restaurant name should match test name.", testRestaurant.name.equals("TEST RESTAURANT"));
        assertEquals("Restaurant stars should match test stars.", 2, testRestaurant.stars);
        assertEquals("Restaurant price category should match test price category.", 3, testRestaurant.priceCategory);
    }

    @Test
    public void testRestaurant_ToString()
    {
        assertEquals(
                "Restaurant toString() should match test toString().",
                "Restaurant name: TEST RESTAURANT\n" +
                         "Stars: 2\n" +
                         "Price Category: 3\n" +
                        "Reviews: [Restaurant name: TEST RESTAURANT\n" +
                        "Review: TEST BODY 1\n" +
                        "Author: Test Author 1\n" +
                        "Stars: 4\n" +
                        ", Restaurant name: TEST RESTAURANT\n" +
                        "Review: TEST BODY 2\n" +
                        "Author: Test Author 2\n" +
                        "Stars: 3\n" +
                        ", Restaurant name: TEST RESTAURANT\n" +
                        "Review: TEST BODY 3\n" +
                        "Author: Test Author 3\n" +
                        "Stars: 2\n" +
                        "]\n",
                         testRestaurant.toString());
    }

    @Test
    public void testRestaurant_AddReview()
    {
        Review testReview4 = new Review("TEST BODY 4", "Test Author 4", 4);

        testRestaurant.addReview(testReview4);

        assertEquals(
                "Restaurant addReview() should successfully add a new review and update the restaurant's stars.",
                "Restaurant name: TEST RESTAURANT\n" +
                        "Stars: 4\n" +
                        "Price Category: 3\n" +
                        "Reviews: [Restaurant name: TEST RESTAURANT\n" +
                        "Review: TEST BODY 1\n" +
                        "Author: Test Author 1\n" +
                        "Stars: 4\n" +
                        ", Restaurant name: TEST RESTAURANT\n" +
                        "Review: TEST BODY 2\n" +
                        "Author: Test Author 2\n" +
                        "Stars: 3\n" +
                        ", Restaurant name: TEST RESTAURANT\n" +
                        "Review: TEST BODY 3\n" +
                        "Author: Test Author 3\n" +
                        "Stars: 2\n" +
                        ", Restaurant name: TEST RESTAURANT\n" +
                        "Review: TEST BODY 4\n" +
                        "Author: Test Author 4\n" +
                        "Stars: 4\n" +
                        "]\n",
                testRestaurant.toString());
    }

    @Test
    public void testReview()
    {
        assertTrue("Review body should match test body.", testReview1.body.equals("TEST BODY 1"));
        assertTrue("Review author should match test author.", testReview1.author.equals("Test Author 1"));
        assertEquals("Review stars should match test stars.", 4, testReview1.stars);
    }

    @Test
    public void testReview_ToString()
    {
        assertEquals(
                "Review toString() should match test toString().",
                "Restaurant name: TEST RESTAURANT\n" +
                        "Review: TEST BODY 1\n" +
                        "Author: Test Author 1\n" +
                        "Stars: 4\n",
                testReview1.toString());
    }
}
