/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import java.awt.*;
import java.util.Arrays;

public class Library {

    public static int[] roll(int n) {
        int[] diceRollsArray = new int[n];

        for(int i = 0; i < n; i++) {
            int diceRoll = (int) Math.ceil(Math.random() * 6);
            diceRollsArray[i] = diceRoll;
        }
        return diceRollsArray;
    }

    public static boolean containsDuplicates(int[] inputArray) {
        for (int i = 0; i < inputArray.length; i++) {
            for (int j = i + 1 ; j < inputArray.length; j++) {
                if (inputArray[i] == inputArray[j]) return true;
            }
        }
        return false;
    }

    public static double calculateAverages(int[] inputArray) {
        if (inputArray.length == 0) return 0.0;

        double arraySum = 0.0;

        for (int numbers : inputArray) {
            arraySum += numbers;
        }
        return arraySum / inputArray.length;
    }

    public static int[] arrayOfLowestAverageValue(int[][] arrayOfArrays) {
        if (arrayOfArrays.length == 0) return new int[]{};

        double lowestAverageArrayValue = calculateAverages(arrayOfArrays[0]);
        int lowestAverageArrayIndex = 0;

        for (int i = 1; i < arrayOfArrays.length; i++) {
            double currentArrayAverage = calculateAverages(arrayOfArrays[i]);

            if (lowestAverageArrayValue > currentArrayAverage) {
                lowestAverageArrayValue = currentArrayAverage;
                lowestAverageArrayIndex = i;
            }
        }
        return arrayOfArrays[lowestAverageArrayIndex];
    }
}
